# Generated by Django 4.2 on 2025-03-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_menu_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login_time',
        ),
    ]
