# Generated by Django 4.2 on 2025-03-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_book_remove_menu_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='extra_users', to='user.permission'),
        ),
    ]
