# Generated by Django 4.2 on 2025-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_extra_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='图标'),
        ),
    ]
