# Generated by Django 4.2 on 2025-03-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_permission_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='API Path'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='方法'),
        ),
    ]
