# Generated by Django 4.2 on 2025-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_permission_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='title',
        ),
    ]
