# Generated by Django 4.2 on 2025-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_name_permission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='button_codes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
