# Generated by Django 4.2 on 2025-06-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_permission_button_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='button_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='user.menu', verbose_name='所属菜单'),
        ),
    ]
