# Generated by Django 4.2 on 2025-06-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_permission_button_codes_alter_permission_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='button_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
