# Generated by Django 4.2 on 2025-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_role_button_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='按钮权限'),
        ),
    ]
