# Generated by Django 4.2 on 2025-01-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='pid',
        ),
    ]
