# Generated by Django 4.2 on 2025-03-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_profile_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.menu', verbose_name='父菜单'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='static/%Y/%m'),
        ),
    ]
