# Generated by Django 4.2 on 2025-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_role_menus_permission_button_codes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='component',
        ),
        migrations.AddField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='组件'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
